# Generated by Django 3.0.2 on 2020-04-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingsite', '0002_auto_20200401_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
