# Generated by Django 3.0.2 on 2020-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingsite', '0003_auto_20200403_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
