# Generated by Django 3.0.2 on 2020-04-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingsite', '0004_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
